apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3
  labels:
    app: test3
    kubernetes.azure.com/generator: devhub
  namespace: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test3
  template:
    metadata:
      labels:
        app: test3
    spec:
      containers:
        - name: test3
          image: testcontainerapp.azurecr.io/testimagebank:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
