apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdep
  labels:
    app: springbootdep
    kubernetes.azure.com/generator: devhub
  namespace: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootdep
  template:
    metadata:
      labels:
        app: springbootdep
    spec:
      containers:
        - name: springbootdep
          image: testcontainerapp.azurecr.io/image-workflow-1735058834581:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
