apiVersion: v1
kind: Service
metadata:
  name: springbootdep
  namespace: bankapp
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: springbootdep
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080