apiVersion: v1
kind: Service
metadata:
  name: testdeploy
  namespace: mydev
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: testdeploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080